table game
	lineageTag: f33b89d3-958d-42fb-adda-a6ef6a703d84

	column date
		dataType: string
		lineageTag: ee42e28f-f798-4f1d-b1ef-5f4ca3096522
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

	column dayAbbrev
		dataType: string
		lineageTag: 25a58bc7-7066-422e-bf60-325ddd3a6c67
		summarizeBy: none
		sourceColumn: dayAbbrev

		annotation SummarizationSetBy = Automatic

	column numberOfGames
		dataType: string
		lineageTag: 69c7821d-601b-4c03-858b-3c4c9b7c6cf7
		summarizeBy: none
		sourceColumn: numberOfGames

		annotation SummarizationSetBy = Automatic

	column datePromo
		dataType: string
		lineageTag: 308da87f-17dc-4db1-9a21-312f75a02474
		summarizeBy: none
		sourceColumn: datePromo

		annotation SummarizationSetBy = Automatic

	column games
		dataType: string
		lineageTag: c6dcf3c0-0be1-4c4b-b7f4-69b86351a188
		summarizeBy: none
		sourceColumn: games

		annotation SummarizationSetBy = Automatic

	partition game = m
		mode: import
		source =
				let
				    headers = [#"Content-type" = "application/json"],
				    result = Web.Contents("https://api-web.nhle.com/v1/schedule/2025-03-01",[Headers = headers]), //TODO: abstract the date to a parameter
				    json = Json.Document(result),
				    game_week = Table.FromRecords(json[gameWeek]),
				    game_week_with_game = Table.ExpandListColumn(game_week,"games"),
				
				    output = game_week_with_game
				in
				    output

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

