table game
	lineageTag: f33b89d3-958d-42fb-adda-a6ef6a703d84

	column id
		dataType: string
		lineageTag: 32580386-9a15-414b-9e25-6e4e42f73089
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column season
		dataType: string
		lineageTag: 3a97ba09-7bc3-4691-8c40-42ec2f16c8a4
		summarizeBy: none
		sourceColumn: season

		annotation SummarizationSetBy = Automatic

	column gameType
		dataType: string
		lineageTag: 66f6af72-620c-40e5-9ed8-8c07f1947366
		summarizeBy: none
		sourceColumn: gameType

		annotation SummarizationSetBy = Automatic

	column limitedScoring
		dataType: string
		lineageTag: a3cebb7d-9b4b-422e-9aee-56ce463bc856
		summarizeBy: none
		sourceColumn: limitedScoring

		annotation SummarizationSetBy = Automatic

	column gameDate
		dataType: string
		lineageTag: 5ecfbe5c-50bc-463b-a2a3-6f17304b8e86
		summarizeBy: none
		sourceColumn: gameDate

		annotation SummarizationSetBy = Automatic

	column venue
		dataType: string
		lineageTag: 76edf2e2-7a44-4893-b81d-7d89054a1193
		summarizeBy: none
		sourceColumn: venue

		annotation SummarizationSetBy = Automatic

	column venueLocation
		dataType: string
		lineageTag: 97645684-6879-46e5-9181-2b01e76244a6
		summarizeBy: none
		sourceColumn: venueLocation

		annotation SummarizationSetBy = Automatic

	column startTimeUTC
		dataType: string
		lineageTag: 6fcf33aa-3645-4137-b51d-2c71ef9f8a74
		summarizeBy: none
		sourceColumn: startTimeUTC

		annotation SummarizationSetBy = Automatic

	column easternUTCOffset
		dataType: string
		lineageTag: fba68d5b-3af0-4a46-806f-567fcdb58f42
		summarizeBy: none
		sourceColumn: easternUTCOffset

		annotation SummarizationSetBy = Automatic

	column venueUTCOffset
		dataType: string
		lineageTag: 1f49a26b-8ad1-42b1-9d92-62ed6afbf692
		summarizeBy: none
		sourceColumn: venueUTCOffset

		annotation SummarizationSetBy = Automatic

	column tvBroadcasts
		dataType: string
		lineageTag: bf8faeeb-c2c3-4ad5-a6d3-c38dc21d94eb
		summarizeBy: none
		sourceColumn: tvBroadcasts

		annotation SummarizationSetBy = Automatic

	column gameState
		dataType: string
		lineageTag: 35b39b78-b9cf-4275-9f09-165f88b233e1
		summarizeBy: none
		sourceColumn: gameState

		annotation SummarizationSetBy = Automatic

	column gameScheduleState
		dataType: string
		lineageTag: 224782f1-f5ac-4987-b377-25581aaf4ded
		summarizeBy: none
		sourceColumn: gameScheduleState

		annotation SummarizationSetBy = Automatic

	column periodDescriptor
		dataType: string
		lineageTag: 6e3f1baa-cc2e-4df6-9315-473433926b2f
		summarizeBy: none
		sourceColumn: periodDescriptor

		annotation SummarizationSetBy = Automatic

	column awayTeam
		dataType: string
		lineageTag: 36a18ecc-99e0-473f-9849-5af50a90467d
		summarizeBy: none
		sourceColumn: awayTeam

		annotation SummarizationSetBy = Automatic

	column homeTeam
		dataType: string
		lineageTag: 43985ded-b3d3-4e94-b214-d8a500c4fbef
		summarizeBy: none
		sourceColumn: homeTeam

		annotation SummarizationSetBy = Automatic

	column shootoutInUse
		dataType: string
		lineageTag: a090a96e-6838-48a3-a07a-9f094d437883
		summarizeBy: none
		sourceColumn: shootoutInUse

		annotation SummarizationSetBy = Automatic

	column otInUse
		dataType: string
		lineageTag: 5ff03bcb-ad6f-4ee7-a2df-6ce71c15d804
		summarizeBy: none
		sourceColumn: otInUse

		annotation SummarizationSetBy = Automatic

	column clock
		dataType: string
		lineageTag: 15c866ad-c2ee-4eae-8fad-abb9fc0d7c85
		summarizeBy: none
		sourceColumn: clock

		annotation SummarizationSetBy = Automatic

	column displayPeriod
		dataType: string
		lineageTag: 3010f9a7-931c-4e81-bd81-6742fb89d295
		summarizeBy: none
		sourceColumn: displayPeriod

		annotation SummarizationSetBy = Automatic

	column maxPeriods
		dataType: string
		lineageTag: 06037b59-9dd8-4f67-9dfe-b254f678a5f6
		summarizeBy: none
		sourceColumn: maxPeriods

		annotation SummarizationSetBy = Automatic

	column gameOutcome
		dataType: string
		lineageTag: 03b4bba3-0b95-4011-a733-ca487a507cc1
		summarizeBy: none
		sourceColumn: gameOutcome

		annotation SummarizationSetBy = Automatic

	column plays
		dataType: string
		lineageTag: c8f9a85e-11d8-4ca8-8366-35f445040a80
		summarizeBy: none
		sourceColumn: plays

		annotation SummarizationSetBy = Automatic

	column rosterSpots
		dataType: string
		lineageTag: 8951bc61-1b30-420b-8466-4554d01433f1
		summarizeBy: none
		sourceColumn: rosterSpots

		annotation SummarizationSetBy = Automatic

	column regPeriods
		dataType: string
		lineageTag: fa08c12d-a91e-4a73-8ae0-a43bb974e9d8
		summarizeBy: none
		sourceColumn: regPeriods

		annotation SummarizationSetBy = Automatic

	column summary
		dataType: string
		lineageTag: d598fecd-e790-42c2-b95d-ba6b92e89dc0
		summarizeBy: none
		sourceColumn: summary

		annotation SummarizationSetBy = Automatic

	partition game = m
		mode: import
		source =
				let
				    A = _fetch_play_by_play("2024020978"),
				    headers = [#"Content-type" = "application/json"],
				    result = Web.Contents("https://api-web.nhle.com/v1/schedule/2025-03-01",[Headers = headers]), //TODO: abstract the date to a parameter
				    json = Json.Document(result),
				    game_week = Table.FromRecords(json[gameWeek]),
				    game_week_with_game = Table.ExpandListColumn(game_week,"games"),
				    game_week_with_game_id = Table.AddColumn(game_week_with_game,"game_id", each Text.From(_[games][id])),
				    game_week_with_game_play_by_play = Table.AddColumn(game_week_with_game_id,"game", each _fetch_play_by_play(_[game_id])),
				    game = Table.FromRecords(Table.Column(game_week_with_game_play_by_play,"game")),
				
				    output = game
				in
				    output

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Exception

