table game
	lineageTag: 88167bcc-0711-4e59-a847-72e93d2cdf11

	column date
		dataType: string
		lineageTag: edbc0cdd-2a41-4a6d-859c-45fff7a11bdd
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

	column dayAbbrev
		dataType: string
		lineageTag: 22e43255-8510-4fd3-85ac-e92eb5df8b3e
		summarizeBy: none
		sourceColumn: dayAbbrev

		annotation SummarizationSetBy = Automatic

	column numberOfGames
		dataType: string
		lineageTag: 8fef1faf-1728-40b1-96ae-a1a032b286fe
		summarizeBy: none
		sourceColumn: numberOfGames

		annotation SummarizationSetBy = Automatic

	column datePromo
		dataType: string
		lineageTag: 76d1f54a-61b6-42e9-a090-591588ab141d
		summarizeBy: none
		sourceColumn: datePromo

		annotation SummarizationSetBy = Automatic

	column games
		dataType: string
		lineageTag: 036bc963-d3f3-45c8-b319-a7a2d1b1a98a
		summarizeBy: none
		sourceColumn: games

		annotation SummarizationSetBy = Automatic

	column game_id
		dataType: string
		lineageTag: 747775dc-3f5e-4e9a-8aab-abdb78be9e89
		summarizeBy: none
		sourceColumn: game_id

		annotation SummarizationSetBy = Automatic

	partition game = m
		mode: import
		source =
				let
				    headers = [#"Content-type" = "application/json"],
				    result = Web.Contents("https://api-web.nhle.com/v1/schedule/2025-03-01",[Headers = headers]), //TODO: abstract the date to a parameter
				    json = Json.Document(result),
				    game_week = Table.FromRecords(json[gameWeek]),
				    expanded_game_week = Table.ExpandListColumn(game_week,"games"),
				    game_week_with_game_id = Table.AddColumn(expanded_game_week, "game_id", each Text.From(_[games][id])),
				
				    output = game_week_with_game_id
				in
				    output

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

