table Points
	lineageTag: 4bb570a5-6772-42a6-a09e-a5ebfcfb54e0

	column GameResult
		dataType: string
		lineageTag: 24c05547-cb33-48b6-861d-6251457b91bb
		summarizeBy: none
		sourceColumn: GameResult

		annotation SummarizationSetBy = Automatic

	column Points
		dataType: int64
		formatString: 0
		lineageTag: 894ade54-500b-421f-8b23-30887c4e9834
		summarizeBy: sum
		sourceColumn: Points

		annotation SummarizationSetBy = Automatic

	partition Points = m
		mode: import
		source =
				let
				    Source = #table(
				        {"GameResult","Points"},
				        {
				            {"Win",2},
				            {"Loss",0},
				            {"Overtime/Shootout Win",2},
				            {"Overtime/Shootout Loss",1}
				        }
				    ),
				
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"GameResult", type text}, {"Points", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

