table spotlight
	lineageTag: e4dc1302-e86e-470d-ae7f-ef71634b2291

	column playerId
		dataType: string
		lineageTag: cc2a2497-9f87-486d-99ce-094da148723e
		summarizeBy: none
		sourceColumn: playerId

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		lineageTag: 9e2fb095-bcdd-4f2f-bc3f-bebfbb0b2c80
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	column playerSlug
		dataType: string
		lineageTag: c8b1aa65-3c91-47d7-94a4-dce51d09da75
		summarizeBy: none
		sourceColumn: playerSlug

		annotation SummarizationSetBy = Automatic

	column position
		dataType: string
		lineageTag: 89c694fe-8a02-4eb9-bfee-0276b6abf50d
		summarizeBy: none
		sourceColumn: position

		annotation SummarizationSetBy = Automatic

	column sweaterNumber
		dataType: string
		lineageTag: 5968524f-65a9-4d19-af60-83540d8146b7
		summarizeBy: none
		sourceColumn: sweaterNumber

		annotation SummarizationSetBy = Automatic

	column teamId
		dataType: string
		lineageTag: a88051de-0dd7-407b-b588-b9b080b968ed
		summarizeBy: none
		sourceColumn: teamId

		annotation SummarizationSetBy = Automatic

	column headshot
		dataType: string
		lineageTag: b4d12054-1e55-4100-ab3e-735e9cc59682
		dataCategory: ImageUrl
		summarizeBy: none
		sourceColumn: headshot

		annotation SummarizationSetBy = Automatic

	column teamTriCode
		dataType: string
		lineageTag: f6581fac-885b-4d00-8a42-fbae46ca3581
		summarizeBy: none
		sourceColumn: teamTriCode

		annotation SummarizationSetBy = Automatic

	column teamLogo
		dataType: string
		lineageTag: 3f06692c-ef9c-44d0-902a-0f10e3c6d1dd
		dataCategory: ImageUrl
		summarizeBy: none
		sourceColumn: teamLogo

		annotation SummarizationSetBy = Automatic

	column sortId
		dataType: string
		lineageTag: 3399dc71-074d-4d43-90a6-4ff59fc4c17e
		summarizeBy: none
		sourceColumn: sortId

		annotation SummarizationSetBy = Automatic

	column default_name
		dataType: string
		lineageTag: fad5252e-18c8-4510-831f-f2d388b90a1d
		summarizeBy: none
		sourceColumn: default_name

		annotation SummarizationSetBy = Automatic

	partition spotlight = m
		mode: import
		source =
				let
				    headers = [#"Content-type" = "application/json"],
				    result = Web.Contents("https://api-web.nhle.com/v1/player-spotlight",[Headers = headers]),
				    json = Json.Document(result),
				    to_table = Table.FromRecords(json),
				    default_name = Table.AddColumn(to_table, "default_name", each [name][default]),
				
				    output = default_name
				in
				    output

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

