table standing_season
	excludeFromModelRefresh
	lineageTag: 2b8e005b-e581-4f2f-be57-c69b9fd18632

	column id
		dataType: string
		lineageTag: d3910ba3-3936-463f-9319-9df075e10c0c
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column conferencesInUse
		dataType: string
		lineageTag: 935c5b10-23e6-4b59-831c-0a9dd3cc349e
		summarizeBy: none
		sourceColumn: conferencesInUse

		annotation SummarizationSetBy = Automatic

	column divisionsInUse
		dataType: string
		lineageTag: 531b16ec-13c8-4c27-803e-9633cc26cf5f
		summarizeBy: none
		sourceColumn: divisionsInUse

		annotation SummarizationSetBy = Automatic

	column pointForOTlossInUse
		dataType: string
		lineageTag: d3de29e7-75a6-4db4-8c60-eeaac7a57b93
		summarizeBy: none
		sourceColumn: pointForOTlossInUse

		annotation SummarizationSetBy = Automatic

	column regulationWinsInUse
		dataType: string
		lineageTag: 39e21a9c-b38f-43e3-8cee-5aa5fd4348dd
		summarizeBy: none
		sourceColumn: regulationWinsInUse

		annotation SummarizationSetBy = Automatic

	column rowInUse
		dataType: string
		lineageTag: 9b8b55e5-388b-4b70-93af-4b6d1934e507
		summarizeBy: none
		sourceColumn: rowInUse

		annotation SummarizationSetBy = Automatic

	column standingsEnd
		dataType: string
		lineageTag: 729705e5-2606-4fb2-9703-348be1ab6aba
		summarizeBy: none
		sourceColumn: standingsEnd

		annotation SummarizationSetBy = Automatic

	column standingsStart
		dataType: string
		lineageTag: 979be7a5-0eff-41eb-b4e7-e3f6b99b4f3d
		summarizeBy: none
		sourceColumn: standingsStart

		annotation SummarizationSetBy = Automatic

	column tiesInUse
		dataType: string
		lineageTag: e0fb362d-690d-46a9-8b8f-fdac2429ebce
		summarizeBy: none
		sourceColumn: tiesInUse

		annotation SummarizationSetBy = Automatic

	column wildcardInUse
		dataType: string
		lineageTag: 8d1982e7-970e-419b-9be4-7be763d587eb
		summarizeBy: none
		sourceColumn: wildcardInUse

		annotation SummarizationSetBy = Automatic

	partition standing_season = m
		mode: import
		source =
				let
				    headers = [#"Content-type" = "application/json"],
				    result = Web.Contents("https://api-web.nhle.com/v1/standings-season?",[Headers = headers]),
				    json = Json.Document(result),
				    standings = Table.FromRecords(json[seasons]),
				
				    output = standings
				in
				    output

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

